services:
  server:
    build:
      context: .
      dockerfile: apps/mock/Dockerfile
    image: ravciok/nx-project-example-server
    container_name: server
    networks:
      - frontend-network

  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    image: ravciok/nx-project-example-client
    container_name: client
    networks:
      - frontend-network
    volumes:
      - www:/usr/share/nginx
    depends_on:
      - server

  proxy:
    build:
      context: .
      dockerfile: apps/proxy/Dockerfile
    image: ravciok/nx-project-example-proxy
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend-network
    volumes:
      - www:/usr/share/nginx
    depends_on:
      - client

volumes:
  www:
networks:
  frontend-network:
    driver: bridge
