name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build and push - server
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ravciok/nx-project-example-server:latest
          context: .
          file: ./apps/mock/Dockerfile
      -
        name: Build and push - client
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ravciok/nx-project-example-client:latest
          context: .
          file: ./apps/client/Dockerfile
      -
        name: Build and push - proxy
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ravciok/nx-project-example-proxy:latest
          context: .
          file: ./apps/proxy/Dockerfile
          
